services:
  - type: web
    name: trading-bot
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_WEBSOCKET
        value: true
      - key: AUTO_TRADE
        value: false
      - key: MAX_POSITIONS
        value: 3
      - key: SIGNAL_COOLDOWN
        value: 300000
      - key: EMA_PERIOD
        value: 20
      - key: RSI_PERIOD
        value: 14
      - key: CONFIDENCE_THRESHOLD
        value: 70
      - key: BREAKOUT_THRESHOLD
        value: 0.3